openapi: 3.1.0
info:
  title: Quickbase Fields API
  version: 1.0.0
  description: Core operations for managing Quickbase fields

servers:
  - url: https://qb-fields.loca.lt
    description: Quickbase Fields Middleware Server (Tunneled)

components:
  schemas: {}
  securitySchemes:
    QuickbaseAuth:
      type: apiKey
      name: x-api-key
      in: header
      description: API key for middleware authentication (must match API_KEY in middleware .env)

security:
  - QuickbaseAuth: []

paths:
  /fields:
    get:
      operationId: getFields
      summary: Get fields for a table
      parameters:
        - name: tableId
          in: query
          required: true
          schema:
            type: string
            description: The unique identifier of the table
            minLength: 1
        - name: includeFieldPerms
          in: query
          required: false
          schema:
            type: boolean
            description: Whether to include field permissions in response
            default: false
      responses:
        '200':
          description: Fields retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: The field ID
                    label:
                      type: string
                      description: The field label/name
                    fieldType:
                      type: string
                      description: The type of field
                    required:
                      type: boolean
                    unique:
                      type: boolean
                    properties:
                      type: object
                      additionalProperties: true
                    permissions:
                      type: array
                      items:
                        type: object
                        properties:
                          role:
                            type: string
                          permissionType:
                            type: string
                          roleId:
                            type: integer

    post:
      operationId: createField
      summary: Create a new field
      parameters:
        - name: tableId
          in: query
          required: true
          schema:
            type: string
            description: The unique identifier of the table
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - label
                - fieldType
              properties:
                label:
                  type: string
                  description: Field label/name
                fieldType:
                  type: string
                  description: Type of field
                  enum:
                    - text
                    - text-multiple-choice
                    - text-multi-line
                    - rich-text
                    - numeric
                    - currency
                    - rating
                    - percent
                    - multitext
                    - email
                    - url
                    - duration
                    - date
                    - datetime
                    - timestamp
                    - timeofday
                    - checkbox
                    - user
                    - multiuser
                    - address
                    - phone
                    - file
                required:
                  type: boolean
                  description: Whether field is required
                unique:
                  type: boolean
                  description: Whether field values must be unique
                properties:
                  type: object
                  description: Field type specific properties
                  additionalProperties: true
                permissions:
                  type: array
                  description: Field permissions per role
                  items:
                    type: object
                    required:
                      - role
                      - permissionType
                    properties:
                      role:
                        type: string
                      permissionType:
                        type: string
                        enum: [None, View, Modify]
                      roleId:
                        type: integer
      responses:
        '200':
          description: Field created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The ID of the created field

    delete:
      operationId: deleteFields
      summary: Delete multiple fields
      parameters:
        - name: tableId
          in: query
          required: true
          schema:
            type: string
            description: The unique identifier of the table
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - fieldIds
              properties:
                fieldIds:
                  type: array
                  description: List of field IDs to delete
                  items:
                    type: integer
      responses:
        '200':
          description: Fields deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  deletedFieldIds:
                    type: array
                    items:
                      type: integer
                  errors:
                    type: array
                    items:
                      type: string

  /fields/{fieldId}:
    get:
      operationId: getField
      summary: Get field details
      parameters:
        - name: fieldId
          in: path
          required: true
          schema:
            type: integer
            description: The unique identifier of the field
        - name: tableId
          in: query
          required: true
          schema:
            type: string
            description: The unique identifier of the table
        - name: includeFieldPerms
          in: query
          required: false
          schema:
            type: boolean
            description: Whether to include field permissions
            default: false
      responses:
        '200':
          description: Field details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  label:
                    type: string
                  fieldType:
                    type: string
                  required:
                    type: boolean
                  unique:
                    type: boolean
                  properties:
                    type: object
                    additionalProperties: true
                  permissions:
                    type: array
                    items:
                      type: object
                      properties:
                        role:
                          type: string
                        permissionType:
                          type: string
                        roleId:
                          type: integer

    post:
      operationId: updateField
      summary: Update field properties
      parameters:
        - name: fieldId
          in: path
          required: true
          schema:
            type: integer
            description: The unique identifier of the field
        - name: tableId
          in: query
          required: true
          schema:
            type: string
            description: The unique identifier of the table
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                label:
                  type: string
                  description: New field label/name
                required:
                  type: boolean
                  description: Whether field is required
                unique:
                  type: boolean
                  description: Whether field values must be unique
                properties:
                  type: object
                  description: Field type specific properties
                  additionalProperties: true
                permissions:
                  type: array
                  description: Field permissions per role
                  items:
                    type: object
                    required:
                      - role
                      - permissionType
                    properties:
                      role:
                        type: string
                      permissionType:
                        type: string
                        enum: [None, View, Modify]
                      roleId:
                        type: integer
      responses:
        '200':
          description: Field updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The ID of the updated field

  /fields/usage:
    get:
      operationId: getFieldsUsage
      summary: Get usage statistics for all fields
      parameters:
        - name: tableId
          in: query
          required: true
          schema:
            type: string
            description: The unique identifier of the table
        - name: skip
          in: query
          required: false
          schema:
            type: integer
            description: Number of fields to skip
            minimum: 0
        - name: top
          in: query
          required: false
          schema:
            type: integer
            description: Maximum number of fields to return
            minimum: 1
      responses:
        '200':
          description: Field usage statistics retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    field:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        type:
                          type: string
                    usage:
                      type: object
                      properties:
                        forms:
                          type: object
                          properties:
                            count:
                              type: integer
                        reports:
                          type: object
                          properties:
                            count:
                              type: integer
                        relationships:
                          type: object
                          properties:
                            count:
                              type: integer

  /fields/usage/{fieldId}:
    get:
      operationId: getFieldUsage
      summary: Get usage statistics for a specific field
      parameters:
        - name: fieldId
          in: path
          required: true
          schema:
            type: integer
            description: The unique identifier of the field
        - name: tableId
          in: query
          required: true
          schema:
            type: string
            description: The unique identifier of the table
      responses:
        '200':
          description: Field usage statistics retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  field:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      type:
                        type: string
                  usage:
                    type: object
                    properties:
                      forms:
                        type: object
                        properties:
                          count:
                            type: integer
                      reports:
                        type: object
                        properties:
                          count:
                            type: integer
                      relationships:
                        type: object
                        properties:
                          count:
                            type: integer
